Repository Sylius/InvoicingPlugin, pull requests merged in 2019-02, with the labels that each got.

#107 Fix coding standards
  spec/Generator/InvoiceGeneratorSpec.php
  src/Generator/InvoiceGenerator.php
  src/Generator/SequentialInvoiceNumberGenerator.php
Labels: Bug

#109 Fix Channel form
  src/Resources/config/services.xml
  src/Resources/views/Channel/shopBillingDataForm.html.twig
Labels: Bug

#110 Make invoice beautiful again
  spec/Generator/InvoicePdfFileGeneratorSpec.php
  src/Generator/InvoicePdfFileGenerator.php
  src/Resources/assets/sylius-logo.png
  src/Resources/config/services.xml
  src/Resources/views/Invoice/Download/pdf.html.twig
Labels: Enhancement

#112 Make it possible to generate invoices for orders placed before plugin installation
  README.md
  docs/legacy_installation.md
  features/managing_invoices/generating_invoices_for_previously_placed_orders.feature
  spec/CommandHandler/SendInvoiceEmailHandlerSpec.php
  spec/Creator/InvoiceCreatorSpec.php
  spec/Creator/MassInvoicesCreatorSpec.php
  spec/EventListener/CreateInvoiceOnOrderPlacedListenerSpec.php
  spec/EventProducer/OrderPaymentPaidProducerSpec.php
  src/Cli/GenerateInvoicesCommand.php
  src/CommandHandler/SendInvoiceEmailHandler.php
  src/Creator/InvoiceCreator.php
  src/Creator/InvoiceCreatorInterface.php
  src/Creator/MassInvoicesCreator.php
  src/Creator/MassInvoicesCreatorInterface.php
  src/EventListener/CreateInvoiceOnOrderPlacedListener.php
  src/EventProducer/OrderPaymentPaidProducer.php
  src/Exception/InvoiceAlreadyGenerated.php
  src/Repository/DoctrineInvoiceRepository.php
  src/Repository/InvoiceRepository.php
  src/Resources/config/services.xml
  tests/Application/config/services_test.yaml
  tests/Application/src/EventProducer/TestOrderPlacedProducer.php
  tests/Behat/Context/Cli/InvoicesGenerationContext.php
  tests/Behat/Context/Domain/GeneratingInvoiceContext.php
  tests/Behat/Context/Ui/Admin/ManagingInvoicesContext.php
  tests/Behat/Context/Ui/Shop/CustomerBrowsingInvoicesContext.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/suites/admin/managing_invoices.yml
Labels: Feature
