Repository Sylius/InvoicingPlugin, pull requests merged in 2021-07, with the labels that each got.

#233 Upgrade to stable Sylius 1.10
  .github/workflows/build.yml
  composer.json
Labels: Maintenance

#231 Save invoices on server during generation
  .gitignore
  README.md
  UPGRADE.md
  ecs.php
  features/managing_invoices/saving_invoices_on_server_during_generation.feature
  spec/Creator/InvoiceCreatorSpec.php
  spec/Email/InvoiceEmailSenderSpec.php
  spec/Generator/InvoiceFileNameGeneratorSpec.php
  spec/Generator/InvoicePdfFileGeneratorSpec.php
  spec/Manager/InvoiceFileManagerSpec.php
  spec/Model/InvoicePdfSpec.php
  spec/Provider/InvoiceFileProviderSpec.php
  src/Creator/InvoiceCreator.php
  src/Email/InvoiceEmailSender.php
  src/Generator/InvoiceFileNameGenerator.php
  src/Generator/InvoiceFileNameGeneratorInterface.php
  src/Generator/InvoicePdfFileGenerator.php
  src/Manager/InvoiceFileManager.php
  src/Manager/InvoiceFileManagerInterface.php
  src/Model/InvoicePdf.php
  src/Provider/InvoiceFileProvider.php
  src/Provider/InvoiceFileProviderInterface.php
  src/Resources/config/config.yml
  src/Resources/config/services.xml
  src/Resources/config/services/actions.xml
  src/Resources/config/services/generators.xml
  src/Ui/Action/DownloadInvoiceAction.php
  tests/Application/package.json
  tests/Behat/Context/Application/ManagingInvoicesContext.php
  tests/Behat/Context/Hook/InvoicesContext.php
  tests/Behat/Context/Setup/ChannelContext.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/suites/admin/managing_invoices.yml
  tests/Behat/Resources/suites/customer.yml
Labels: Enhancement, Feature

#232 Do not require visibility in PHPSpec functions
  spec/Command/SendInvoiceEmailSpec.php
  spec/CommandHandler/SendInvoiceEmailHandlerSpec.php
  spec/Converter/BillingDataConverterSpec.php
  spec/Converter/InvoiceShopBillingDataConverterSpec.php
  spec/Converter/LineItemsConverterSpec.php
  spec/Converter/TaxItemsConverterSpec.php
  spec/Creator/InvoiceCreatorSpec.php
  spec/Creator/MassInvoicesCreatorSpec.php
  spec/Entity/BillingDataSpec.php
  spec/Entity/InvoiceSpec.php
  spec/Entity/LineItemSpec.php
  spec/Entity/TaxItemSpec.php
  spec/Event/OrderPaymentPaidSpec.php
  spec/Event/OrderPlacedSpec.php
  spec/EventListener/CreateInvoiceOnOrderPlacedListenerSpec.php
  spec/EventListener/OrderPaymentPaidListenerSpec.php
  spec/EventProducer/OrderPaymentPaidProducerSpec.php
  spec/EventProducer/OrderPlacedProducerSpec.php
  spec/Factory/InvoiceFactorySpec.php
  spec/Generator/InvoiceGeneratorSpec.php
  spec/Generator/InvoicePdfFileGeneratorSpec.php
  spec/Generator/SequentialInvoiceNumberGeneratorSpec.php
  spec/Generator/UuidInvoiceIdentifierGeneratorSpec.php
  spec/Model/InvoicePdfSpec.php
  spec/Provider/ChannelColorProviderSpec.php
  spec/Security/Voter/InvoiceVoterSpec.php
Labels: Enhancement

#230 change information on WKHTMLTOPDF_PATH in README
  README.md
Labels: Maintenance

#238 Extract wkhtmltopdf file path to env variable
  composer.json
  tests/Application/.env
  tests/Application/.env.test
  tests/Application/config/packages/dev/knp_snappy.yaml
  tests/Application/config/packages/knp_snappy.yaml
  tests/Application/config/packages/test/knp_snappy.yaml
Labels: Maintenance
