Repository Sylius/InvoicingPlugin, pull requests merged in 2021-08, with the labels that each got.

#240 Remove unneeded TemporaryFilesystem service
  src/Filesystem/TemporaryFilesystem.php
Labels: Enhancement

#241 Add note to UPGRADE filem about removing TemporaryFilesystem
  UPGRADE.md
Labels: Maintenance

#246 [Invoice] Add payment status
  UPGRADE.md
  features/managing_invoices/seeing_payment_state_on_invoice.feature
  spec/Entity/InvoiceSpec.php
  spec/Factory/InvoiceFactorySpec.php
  spec/Generator/InvoiceGeneratorSpec.php
  src/Entity/Invoice.php
  src/Entity/InvoiceInterface.php
  src/Factory/InvoiceFactory.php
  src/Factory/InvoiceFactoryInterface.php
  src/Generator/InvoiceGenerator.php
  src/Migrations/Version20210812125029.php
  src/Resources/config/doctrine/Invoice.orm.xml
  src/Resources/translations/messages.en.yml
  src/Resources/views/Invoice/Download/pdf.html.twig
  src/Resources/views/Invoice/show.html.twig
  tests/Behat/Context/Ui/Admin/ManagingInvoicesContext.php
  tests/Behat/Page/Admin/Invoice/ShowPage.php
  tests/Behat/Page/Admin/Invoice/ShowPageInterface.php
Labels: Feature

#247 Update knp snappy file
  tests/Application/config/packages/knp_snappy.yaml
Labels: Enhancement
