Repository Sylius/InvoicingPlugin, pull requests merged in 2021-06, with the labels that each got.

#223 Drop support for Sylius 1.8
  .github/workflows/build.yml
  behat.yml.dist
  composer.json
  tests/Application/config/bundles.php
  tests/Application/config/packages/dev/jms_serializer.yaml
  tests/Application/config/packages/jms_serializer.yaml
  tests/Application/config/packages/prod/jms_serializer.yaml
  tests/Application/config/packages/security.yaml
  tests/Application/config/packages/security_checker.yaml
  tests/Application/config/routes/sylius_admin.yaml
  tests/Application/config/sylius/1.8/bundles.php
  tests/Application/config/sylius/1.8/packages/dev/jms_serializer.yaml
  tests/Application/config/sylius/1.8/packages/framework.yaml
  tests/Application/config/sylius/1.8/packages/jms_serializer.yaml
  tests/Application/config/sylius/1.8/packages/prod/jms_serializer.yaml
  tests/Application/config/sylius/1.8/routes/dev/twig.yaml
  tests/Application/config/sylius/1.9/bundles.php
  tests/Application/src/Kernel.php
Labels: Maintenance

#224 Add support for Sylius 1.10 + require PHP ^7.4 || ^8.0
  .github/workflows/build.yml
  composer.json
  phpstan.neon
  tests/Application/config/bundles.php
  tests/Application/config/packages/_sylius.yaml
  tests/Application/config/packages/fos_rest.yaml
  tests/Application/config/packages/security.yaml
  tests/Application/config/packages/test_cached/fos_rest.yaml
  tests/Application/config/routes/sylius_admin_api.yaml
Labels: Maintenance

#226 Relate Invoice with Order
  UPGRADE.md
  spec/CommandHandler/SendInvoiceEmailHandlerSpec.php
  spec/Creator/InvoiceCreatorSpec.php
  spec/Entity/InvoiceSpec.php
  spec/EventProducer/OrderPaymentPaidProducerSpec.php
  spec/Factory/InvoiceFactorySpec.php
  spec/Generator/InvoiceGeneratorSpec.php
  src/CommandHandler/SendInvoiceEmailHandler.php
  src/Creator/InvoiceCreator.php
  src/Doctrine/ORM/InvoiceRepository.php
  src/Doctrine/ORM/InvoiceRepositoryInterface.php
  src/Entity/Invoice.php
  src/Entity/InvoiceInterface.php
  src/EventProducer/OrderPaymentPaidProducer.php
  src/Factory/InvoiceFactory.php
  src/Factory/InvoiceFactoryInterface.php
  src/Generator/InvoiceGenerator.php
  src/Migrations/Version20210607115930.php
  src/Resources/config/doctrine/Invoice.orm.xml
  src/Resources/views/Invoice/Email/invoiceGenerated.html.twig
  src/Resources/views/Invoice/Show/_header.html.twig
  tests/Behat/Context/Domain/GeneratingInvoiceContext.php
  tests/Behat/Context/Ui/Admin/ManagingInvoicesContext.php
  tests/Behat/Context/Ui/Shop/CustomerBrowsingInvoicesContext.php
Labels: Enhancement

#220 Polish translations & invoice download template update
  src/Resources/translations/flashes.pl.yml
  src/Resources/translations/messages.pl.yml
  src/Resources/translations/validators.pl.yml
  src/Resources/views/Invoice/Download/pdf.html.twig
Labels: Enhancement

#228 Fix sorting and filtering invoices by order in the grid
  src/Resources/config/config.yml
Labels: Bug
