Repository Sylius/InvoicingPlugin, pull requests merged in 2021-09, with the labels that each got.

#250 [Maintenance] Remove wrong return types
  phpstan.neon
  src/Entity/InvoiceShopBillingData.php
  src/Entity/InvoiceShopBillingDataInterface.php
  src/Entity/LineItem.php
  src/Entity/LineItemInterface.php
  src/Entity/TaxItem.php
  src/Entity/TaxItemInterface.php
Labels: Maintenance

#249 Use PHP 7.4 syntax
  composer.json
  src/Cli/GenerateInvoicesCommand.php
  src/Command/SendInvoiceEmail.php
  src/CommandHandler/SendInvoiceEmailHandler.php
  src/Creator/InvoiceCreator.php
  src/Creator/MassInvoicesCreator.php
  src/Email/InvoiceEmailSender.php
  src/Entity/BillingData.php
  src/Entity/Invoice.php
  src/Entity/InvoiceSequence.php
  src/Entity/InvoiceShopBillingData.php
  src/Entity/LineItem.php
  src/Entity/TaxItem.php
  src/Event/OrderPaymentPaid.php
  src/Event/OrderPlaced.php
  src/EventListener/CreateInvoiceOnOrderPlacedListener.php
  src/EventListener/OrderPaymentPaidListener.php
  src/EventProducer/OrderPaymentPaidProducer.php
  src/EventProducer/OrderPlacedProducer.php
  src/Factory/InvoiceFactory.php
  src/Form/Type/ChannelFilterType.php
  src/Generator/InvoiceGenerator.php
  src/Generator/InvoicePdfFileGenerator.php
  src/Generator/SequentialInvoiceNumberGenerator.php
  src/Manager/InvoiceFileManager.php
  src/Model/InvoicePdf.php
  src/Provider/ChannelColorProvider.php
  src/Provider/InvoiceFileProvider.php
  src/Security/Voter/InvoiceVoter.php
  src/Twig/ChannelColorExtension.php
  src/Ui/Action/Admin/ResendInvoiceAction.php
  src/Ui/Action/DownloadInvoiceAction.php
  src/Ui/RedirectToOrderShowAction.php
  tests/Behat/Context/Application/ManagingInvoicesContext.php
  tests/Behat/Context/Cli/InvoicesGenerationContext.php
  tests/Behat/Context/Domain/GeneratingInvoiceContext.php
  tests/Behat/Context/Domain/InvoiceEmailContext.php
  tests/Behat/Context/Hook/InvoicesContext.php
  tests/Behat/Context/Order/OrderContext.php
  tests/Behat/Context/Setup/ChannelContext.php
  tests/Behat/Context/Setup/OrderContext.php
  tests/Behat/Context/Ui/Admin/ManagingChannelsContext.php
  tests/Behat/Context/Ui/Admin/ManagingInvoicesContext.php
  tests/Behat/Context/Ui/Shop/CustomerBrowsingInvoicesContext.php
  tests/Behat/Page/Admin/Invoice/ShowPage.php
Labels: Enhancement

#251 New PDF layout
  src/Resources/assets/sylius-logo.png
  src/Resources/views/Invoice/Download/pdf.html.twig
  src/Resources/views/Invoice/Download/pdfLayout.html.twig
Labels: UX/UI

#252 [Behat] Fix type of show page
  tests/Behat/Context/Ui/Admin/ManagingInvoicesContext.php
Labels: Enhancement

#253 [Maintenance] Minor installation guide improvements
  README.md
  docs/legacy_installation.md
Labels: Maintenance, DX
