Repository Sylius/InvoicingPlugin, pull requests merged in 2022-09, with the labels that each got.

#289 Fix down method of migration that changes indexes
  src/Migrations/Version20191216134233.php
Labels: Bug

#290 Drop support for Sylius 1.10
  .github/workflows/build.yml
  composer.json
Labels: Maintenance, Dependencies

#291 [Behat][Invoice] Fix usage of method checking line items after last changes
  tests/Behat/Context/Ui/Admin/ManagingInvoicesContext.php
Labels: Bug, Behat

#293 [Maintenance] Remove redundant configuration for not supported Sylius 1.10
  tests/Application/config/bundles.php
  tests/Application/src/Kernel.php
Labels: Maintenance
