Repository Sylius/InvoicingPlugin, pull requests merged in 2024-11, with the labels that each got.

#330 [Maintenance] Fix CI builds
  .github/workflows/build.yml
Labels: Maintenance

#333 Remove deprecated method + bump to stable Sylius 1.14 + minor clean up
  .github/workflows/build.yml
  UPGRADE.md
  composer.json
  spec/Security/Voter/InvoiceVoterSpec.php
  src/Entity/Invoice.php
  src/Entity/InvoiceInterface.php
  src/Resources/config/config.yml
  src/Security/Voter/InvoiceVoter.php
  src/Ui/Action/Admin/ResendInvoiceAction.php
  tests/Application/config/packages/doctrine.yaml
  tests/Application/config/packages/sylius_invoicing.yaml
  tests/Application/src/Entity/SyliusInvoicingPlugin/BillingData.php
  tests/Application/src/Entity/SyliusInvoicingPlugin/BillingDataInterface.php
  tests/Application/src/Entity/SyliusInvoicingPlugin/Invoice.php
  tests/Application/src/Entity/SyliusInvoicingPlugin/InvoiceInterface.php
  tests/Application/src/Entity/SyliusInvoicingPlugin/InvoiceSequence.php
  tests/Application/src/Entity/SyliusInvoicingPlugin/InvoiceSequenceInterface.php
  tests/Application/src/Entity/SyliusInvoicingPlugin/InvoiceShopBillingData.php
  tests/Application/src/Entity/SyliusInvoicingPlugin/InvoiceShopBillingDataInterface.php
  tests/Application/src/Entity/SyliusInvoicingPlugin/LineItem.php
  tests/Application/src/Entity/SyliusInvoicingPlugin/LineItemInterface.php
  tests/Application/src/Entity/SyliusInvoicingPlugin/TaxItem.php
  tests/Application/src/Entity/SyliusInvoicingPlugin/TaxItemInterface.php
Labels: Maintenance

#334 [Behat] Use Chrome instead of Selenium driver
  CONFLICTS.md
  behat.yml.dist
  composer.json
Labels: Maintenance, Behat, Dependencies

#332 Bump to stable Sylius 2.0 + minor clean up
  .github/workflows/build.yaml
  CHANGELOG.md
  UPGRADE-2.0.md
  composer.json
  src/DependencyInjection/Compiler/SymfonyClockCompilerPass.php
  src/Resources/config/app/twig_hooks/shop/order/summary.yaml
  src/SyliusInvoicingPlugin.php
Labels: Maintenance

#336 Remove trademark and logo part from LICENSE file
  LICENSE
Labels: Maintenance

#337 [CI] Update builds' matrix
  .github/workflows/build.yml
Labels: Maintenance

#341 Fix and make consistent the translation keys
  README.md
  UPGRADE.md
  src/Resources/config/app/routing/admin_invoicing.yml
  src/Resources/config/config.yml
  src/Resources/config/validation.xml
  src/Resources/translations/flashes.de.yml
  src/Resources/translations/flashes.en.yml
  src/Resources/translations/flashes.pl.yml
  src/Resources/translations/messages.de.yml
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
  src/Resources/translations/messages.pl.yml
  src/Resources/translations/validators.de.yml
  src/Resources/translations/validators.en.yml
  src/Resources/translations/validators.pl.yml
  src/Resources/views/Invoice/Admin/_downloadButton.html.twig
  src/Resources/views/Invoice/Admin/_resendButton.html.twig
  src/Resources/views/Invoice/Download/pdf.html.twig
  src/Resources/views/Invoice/Show/_billingData.html.twig
  src/Resources/views/Invoice/Show/_breadcrumb.html.twig
  src/Resources/views/Invoice/Show/_header.html.twig
  src/Resources/views/Invoice/Show/_shopBillingData.html.twig
  src/Resources/views/Invoice/show.html.twig
  src/Resources/views/Order/Admin/_invoices.html.twig
  src/Resources/views/Order/Shop/_downloadButton.html.twig
  src/Resources/views/Order/Shop/_invoices.html.twig
  src/Ui/Action/Admin/ResendInvoiceAction.php
  src/Ui/Menu/AdminMenuListener.php
Labels: Maintenance

#340 Minor improvements and clean up
  spec/CommandHandler/SendInvoiceEmailHandlerSpec.php
  spec/EventProducer/OrderPlacedProducerSpec.php
  src/Cli/GenerateInvoicesCommand.php
  src/CommandHandler/SendInvoiceEmailHandler.php
  src/Email/InvoiceEmailSender.php
  src/EventProducer/OrderPlacedProducer.php
  src/Fixture/Factory/ShopBillingDataExampleFactory.php
  src/Fixture/ShopBillingDataFixture.php
Labels: Enhancement, DX

#339 [Admin] Remove unneeded route + grid improvements
  UPGRADE.md
  src/Resources/config/app/routing/admin_invoicing.yml
  src/Resources/config/config.yml
  src/Resources/config/services/ui.xml
  src/Resources/views/Invoice/Grid/Field/channel.html.twig
  src/Resources/views/Invoice/Grid/Field/orderNumber.html.twig
  src/Ui/RedirectToOrderShowAction.php
Labels: Enhancement, Maintenance

#338 [Admin] Replace custom invoice_channel filter with entity filter from GridBundle
  UPGRADE.md
  src/Form/Type/ChannelFilterType.php
  src/Grid/Filter/ChannelFilter.php
  src/Resources/config/config.yml
  src/Resources/config/services/ui.xml
  src/Resources/views/Grid/Filter/channel.html.twig
  tests/Behat/Page/Admin/Invoice/IndexPage.php
Labels: Enhancement

#342 Reorganize directory structure
  UPGRADE.md
  assets/sylius-logo.png
  config/admin_routes.yaml
  config/config.yaml
  config/doctrine/BillingData.orm.xml
  config/doctrine/Invoice.orm.xml
  config/doctrine/InvoiceSequence.orm.xml
  config/doctrine/InvoiceShopBillingData.orm.xml
  config/doctrine/LineItem.orm.xml
  config/doctrine/TaxItem.orm.xml
  config/services.xml
  config/services/actions.xml
  config/services/cli.xml
  config/services/converters.xml
  config/services/fixtures.xml
  config/services/generators.xml
  config/services/listeners.xml
  config/services/listeners/workflow.xml
  config/services/ui.xml
  config/shop_routes.yaml
  config/validation.xml
  docs/legacy_installation.md
  spec/Generator/InvoicePdfFileGeneratorSpec.php
  src/DependencyInjection/SyliusInvoicingExtension.php
  src/SyliusInvoicingPlugin.php
  templates/Invoice/Admin/_downloadButton.html.twig
  templates/Invoice/Admin/_resendButton.html.twig
  templates/Invoice/Download/pdf.html.twig
  templates/Invoice/Download/pdfLayout.html.twig
  templates/Invoice/Email/invoiceGenerated.html.twig
  templates/Invoice/Show/_backButton.html.twig
  templates/Invoice/Show/_billingData.html.twig
  templates/Invoice/Show/_breadcrumb.html.twig
  templates/Invoice/Show/_header.html.twig
  templates/Invoice/Show/_shopBillingData.html.twig
  templates/Invoice/show.html.twig
  templates/Order/Admin/_invoices.html.twig
  templates/Order/Admin/fetchInvoices.html.twig
  templates/Order/Shop/_downloadButton.html.twig
  templates/Order/Shop/_invoices.html.twig
  templates/Order/Shop/fetchInvoices.html.twig
  tests/Application/config/packages/_sylius.yaml
  tests/Application/config/packages/sylius_invoicing.yaml
  tests/Application/config/routes/sylius_invoicing_plugin.yaml
  tests/DependencyInjection/SyliusInvoicingExtensionTest.php
  translations/flashes.de.yml
  translations/flashes.en.yml
  translations/flashes.pl.yml
  translations/messages.de.yml
  translations/messages.en.yml
  translations/messages.fr.yml
  translations/messages.pl.yml
  translations/validators.de.yml
  translations/validators.en.yml
  translations/validators.pl.yml
Labels: Maintenance

#344 Fix translations' keys after upmerge
  config/config.yaml
  templates/admin/invoice/show/content/header/title_block/title/number.html.twig
  templates/admin/invoice/show/content/header/title_block/title/subtitle.html.twig
  templates/admin/invoice/show/content/sections/buyer.html.twig
  templates/admin/invoice/show/content/sections/card/footer.html.twig
  templates/admin/invoice/show/content/sections/seller.html.twig
  templates/admin/order/show/content/sections/invoices/table.html.twig
  templates/admin/shared/action/download.html.twig
  templates/admin/shared/action/resend.html.twig
  templates/shop/order/show/content/summary/invoices/card/body/table/head/issued_at.html.twig
  templates/shop/order/show/content/summary/invoices/card/head.html.twig
Labels: Bug

#345 [Admin] Fix translations on Invoice index page
  config/admin_routes.yaml
Labels: UX/UI

#343 Regenerate migrations and add support for Postgres
  .github/workflows/build.yml
  UPGRADE.md
  src/Migrations/Version20180625120743.php
  src/Migrations/Version20180626120743.php
  src/Migrations/Version20180711070226.php
  src/Migrations/Version20180711084815.php
  src/Migrations/Version20180801083047.php
  src/Migrations/Version20180826064735.php
  src/Migrations/Version20190103134228.php
  src/Migrations/Version20190604071441.php
  src/Migrations/Version20190607001446.php
  src/Migrations/Version20190607002945.php
  src/Migrations/Version20191016124548.php
  src/Migrations/Version20191216134233.php
  src/Migrations/Version20210607115930.php
  src/Migrations/Version20210729071327.php
  src/Migrations/Version20210812125029.php
  src/Migrations/Version20220811054008.php
  src/Migrations/Version20241121125624.php
Labels: Feature, Maintenance

#347 [CI] Enable composer analyse
  .github/workflows/build.yaml
  src/Twig/Component/Invoice/ListComponent.php
Labels: Maintenance

#348 Adjust the translations and routes after naming convention changes
  config/services/twig.xml
  config/winzou_state_machine.php
  templates/admin/invoice/show/content/header/title_block/actions/back_to_index.html.twig
  templates/admin/invoice/show/content/header/title_block/title/subtitle.html.twig
  templates/admin/invoice/show/content/sections/card/body/table/footer/net_total.html.twig
  templates/admin/invoice/show/content/sections/card/body/table/footer/tax_items.html.twig
  templates/admin/invoice/show/content/sections/card/body/table/footer/taxes_total.html.twig
  templates/admin/invoice/show/content/sections/card/body/table/header/discounted_unit_net_price.html.twig
  templates/admin/invoice/show/content/sections/card/body/table/header/gross_value.html.twig
  templates/admin/invoice/show/content/sections/card/body/table/header/net_value.html.twig
  templates/admin/invoice/show/content/sections/card/body/table/header/no.html.twig
  templates/admin/invoice/show/content/sections/card/body/table/header/tax_amount.html.twig
  templates/admin/invoice/show/content/sections/card/body/table/header/tax_rate.html.twig
  templates/admin/invoice/show/content/sections/card/body/table/header/unit_net_price.html.twig
  templates/admin/order/show/content/sections/invoices/table/body/number.html.twig
  templates/admin/order/show/content/sections/invoices/table/head/issued_at.html.twig
  templates/admin/shared/action/download.html.twig
  templates/admin/shared/action/resend.html.twig
  templates/shop/order/show/content/summary/invoices/card/body/table/body/download.html.twig
  tests/Behat/Resources/services.xml
Labels: Maintenance

#350 Upgrade file fixes
  UPGRADE.md
Labels: Maintenance

#349 Make services private by default
  UPGRADE.md
  config/services.xml
  config/services/actions.xml
  config/services/cli.xml
  config/services/converters.xml
  config/services/fixtures.xml
  config/services/generators.xml
  config/services/listeners.xml
  config/services/listeners/workflow.xml
  config/services/ui.xml
Labels: Maintenance, DX

#351 Move StateMachineAbstraction config to the proper directory in the test application
  tests/Application/config/packages/sylius_state_machine_abstraction.yaml
Labels: Maintenance
