Repository Sylius/InvoicingPlugin, pull requests merged in 2025-01, with the labels that each got.

#365 [Composer] Remove explicit sylius/twig-hooks dependency
  composer.json
Labels: Maintenance, Dependencies

#366 SYL-4253: Flags fix
  templates/admin/invoice/show/content/sections/buyer/country_code.html.twig
  templates/admin/invoice/show/content/sections/seller/country_code.html.twig
Labels: UX/UI

#367 Remove charset in regenerated migrations to be compatible with Sylius
  src/Migrations/Version20180625120743.php
Labels: Maintenance

#368 Revert regenerating migrations in 1.0
  src/Migrations/Version20180625120743.php
  src/Migrations/Version20180626120743.php
  src/Migrations/Version20180711070226.php
  src/Migrations/Version20180711084815.php
  src/Migrations/Version20180801083047.php
  src/Migrations/Version20180826064735.php
  src/Migrations/Version20190103134228.php
  src/Migrations/Version20190604071441.php
  src/Migrations/Version20190607001446.php
  src/Migrations/Version20190607002945.php
  src/Migrations/Version20191016124548.php
  src/Migrations/Version20191216134233.php
  src/Migrations/Version20210607115930.php
  src/Migrations/Version20210729071327.php
  src/Migrations/Version20210812125029.php
  src/Migrations/Version20220811054008.php
Labels: Maintenance

#369 Bring back regenerating migrations in 2.0
  src/Migrations/Version20180625120743.php
  src/Migrations/Version20180626120743.php
  src/Migrations/Version20180711070226.php
  src/Migrations/Version20180711084815.php
  src/Migrations/Version20180801083047.php
  src/Migrations/Version20180826064735.php
  src/Migrations/Version20190103134228.php
  src/Migrations/Version20190604071441.php
  src/Migrations/Version20190607001446.php
  src/Migrations/Version20190607002945.php
  src/Migrations/Version20191016124548.php
  src/Migrations/Version20191216134233.php
  src/Migrations/Version20210607115930.php
  src/Migrations/Version20210729071327.php
  src/Migrations/Version20210812125029.php
  src/Migrations/Version20220811054008.php
Labels: Maintenance
